services:
  nvim:
    image: danding19931115/nvim-lerko
    container_name: nvim-lerko
    network_mode: host
    volumes:
      - D:\coder:/workspace
    tty: true
    stdin_open: true
  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    network_mode: host
    environment:
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./data:/app/data  # 持久化数据
