services:
  nvim:
    image: danding19931115/nvim-lerko:0.0.2
    container_name: nvim-lerko
    ports:
      - "80:80"
    volumes:
      - ${HOME}/.config/nvim/docker/plugged:/root/.config/nvim/plugged
      - ${HOME}/development:/workspace
    tty: true
    stdin_open: true
  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    ports:
      - "8080:8080"  # 服务端口
    environment:
      - SYNC_CLIPBOARD_PORT=8080
      - SYNC_CLIPBOARD_SECRET=1234
    volumes:
      - ./data:/app/data  # 持久化数据
