services:
  nvim:
    image: danding19931115/nvim-lerko
    container_name: nvim-lerko
    network_mode: "host"
    volumes:
      - D:\coder:/workspace
      # Go 缓存持久化
      - go-mod-cache:/root/go/pkg/mod
      - cache:/root/.cache
      - ./script:/tmp/script
    tty: true
    stdin_open: true
  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    ports:
      - "5033:5033"  # 改为端口映射
    environment:
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./data:/app/data  # 持久化数据

volumes:
  go-mod-cache:
  cache:
  workspace:

