services:
  nvim:
    image: danding19931115/nvim-lerko:0.0.2
    container_name: nvim-lerko
    ports:
      - "80:8081"
    volumes:
      - ${HOME}/.config/nvim/docker/plugged:/root/.config/nvim/plugged
      - ${HOME}/developer-env:/workspace
    tty: true
    stdin_open: true
  syncclipboard:
    image: hub.rat.dev/jericx/syncclipboard-server
    container_name: syncclipboard
    restart: unless-stopped
    ports:
      - "5033:5033"  # 服务端口
    volumes:
      - ./data:/app/data  # 持久化数据
